import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import TransferCard from "components/transfer-card";
import ChameleonText from "components/chameleon-text";
import { useState } from "react";

const list = [0, 1, 2];

const Content = () => {
  const [range, setRange] = useState("0");
  return (
    <div className={styles.content}>
      <div style={{ flex: 1 }}>
        <ChameleonText ratio={parseInt(range)} targetRGB={[255, 0, 51]}>
          啊波次的而佛歌
        </ChameleonText>
      </div>
      <div className={styles.bottomBar}>
        <input
          style={{ width: 160 }}
          type="range"
          value={range}
          onChange={(e) => setRange(e.target.value)}
        />
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <TransferCard
          width="100%"
          height="100%"
          list={list}
          itemKey={(item) => item.toString()}
        >
          {() => <Content />}
        </TransferCard>
      </main>
    </div>
  );
};

export default Home;
